Export terraform_version as an output (#4)
**Changes**

- Adds and exports the output version
- Unlinks pre-installed terraform only if file exists
- Docs updates

Closes https://github.com/stv-io/action-tfswitch/issues/2
Closes https://github.com/stv-io/action-tfswitch/issues/3

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -63,3 +63,23 @@ jobs:
           EOF
           tfswitch
           terraform --version
+
+  test-export-version-as-output:
+    runs-on: ubuntu-latest
+    outputs:
+      terraform_version: ${{ steps.tfswitch-install.outputs.terraform_version }}
+    steps:
+    - uses: actions/checkout@v4
+    - name: Setup tfswitch
+      uses: ./
+      id: tfswitch-install
+    - name: Install
+      run: |
+        tfswitch 1.6.6
+        terraform --version
+        if [[ -n "${{ steps.tfswitch-install.outputs.terraform_version }}" ]]; then
+          echo "Terraform ${{ steps.tfswitch-install.outputs.terraform_version }} installed to $(which terraform) .."
+        else
+          echo "Error - expected action output variable is empty"
+          exit 1
+        fi
